<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	  <UserSecretsId>8e4ec7e1-6c7d-46ba-b03f-2f6b0b608585</UserSecretsId>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
		<PackageReference Include="Refit" />
		<PackageReference Include="Refit.HttpClientFactory" />
		<PackageReference Include="Westwind.AspNetCore.LiveReload" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\ShoppeeEcommerce.SharedViewModels\ShoppeeEcommerce.SharedViewModels.csproj" />
	</ItemGroup>
	<Target Name="BuildCSS" BeforeTargets="Build">
		<Exec Command="npm run build" />
	</Target>
</Project>